swagger:
  enable: true

spring:
  profiles:
    active: @profiles.active@
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapping/*DAO.xml
  type-aliases-package: com.sk.gz.entity
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


